################################################################################
# \file recipe_ide_common.mk
#
# \brief
# This make file defines the IDE export variables and target.
#
################################################################################
# \copyright
# Copyright (c) 2018-2026, Infineon Technologies AG, or an affiliate of
# Infineon Technologies AG. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

ifeq ($(WHICHFILE),true)
$(info Processing $(lastword $(MAKEFILE_LIST)))
endif

_MTB_RECIPE__IDE_PRJ_DIR_NAME:=$(notdir $(realpath $(MTB_TOOLS__PRJ_DIR)))


ifeq ($(firstword $(MTB_APPLICATION_SUBPROJECTS)),$(_MTB_RECIPE__IDE_PRJ_DIR_NAME))
_MTB_RECIPE__IS_FIRST_PRJ=1
endif
ifeq ($(lastword $(MTB_APPLICATION_SUBPROJECTS)),$(_MTB_RECIPE__IDE_PRJ_DIR_NAME))
_MTB_RECIPE__IS_LAST_PRJ=1
endif

##############################################
# VSCode Eclipse
##############################################
_MTB_RECIPE__IDE_CORE_SCRIPT_DIR:=$(MTB_TOOLS__CORE_DIR)/make/scripts/$(_MTB_RECIPE__IDE_EXPORT_INTERFACE_VERSION)
_MTB_RECIPE__IDE_TEMPLATE_DIR:=$(MTB_TOOLS__RECIPE_DIR)/make/scripts/$(_MTB_RECIPE__IDE_EXPORT_INTERFACE_VERSION)
_MTB_RECIPE__IDE_BUILD_PATH_RELATIVE:=$(notdir $(MTB_TOOLS__OUTPUT_BASE_DIR))/last_config
_MTB_RECIPE__IDE_BUILD_APPLICATION_PATH_RELATIVE:=$(notdir $(MTB_TOOLS__PRJ_DIR))/$(_MTB_RECIPE__IDE_BUILD_PATH_RELATIVE)
_MTB_RECIPE__IDE_COMBINED_HEX_RELATIVE:=$(patsubst $(call mtb__path_normalize,$(MTB_TOOLS__PRJ_DIR)/../)/%,%,$(_MTB_RECIPE__APP_HEX_FILE))
_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE=$(MTB_TOOLS__OUTPUT_CONFIG_DIR)/recipe_ide_commom_text_data.txt
_MTB_RECIPE__ECLIPSE_COMMON_REGEX_DATA_FILE=$(MTB_TOOLS__OUTPUT_CONFIG_DIR)/recipe_eclipse_commom_template_regex_data.txt

# This is used for combiner-signer single-core projects in order to add proper Erase tasks to VSCode.
# Redefine in specific recipe if needed (e.g. for external memory erase support).
_MTB_RECIPE__VSCODE_TASKS_ERASE_MEMORIES_SUPPORTED?=internal

##############################################
# VSCode
##############################################
_MTB_RECIPE__VSCODE_GCC_BASE_DIR:=$(subst $(MTB_TOOLS__TOOLS_DIR)/,$${config:modustoolbox.toolsPath}/,$(MTB_TOOLCHAIN_GCC_ARM__BASE_DIR))
_MTB_RECIPE__VSCODE_HEX_FILE_APPLICATION:=$(_MTB_RECIPE__IDE_COMBINED_HEX_RELATIVE)
_MTB_RECIPE__VSCODE_ELF_FILE_APPLICATION:=$(_MTB_RECIPE__IDE_BUILD_APPLICATION_PATH_RELATIVE)/$(APPNAME).$(MTB_RECIPE__SUFFIX_TARGET)
_MTB_RECIPE__VSCODE_HEX_FILE:=$(_MTB_RECIPE__IDE_BUILD_PATH_RELATIVE)/$(APPNAME).$(MTB_RECIPE__SUFFIX_PROGRAM)
_MTB_RECIPE__VSCODE_ELF_FILE:=$(_MTB_RECIPE__IDE_BUILD_PATH_RELATIVE)/$(APPNAME).$(MTB_RECIPE__SUFFIX_TARGET)
# Default: hide the Advanced KitProg3 Programming task. Recipes that support it override to false.
_MTB_RECIPE__HIDE_ADVANCED_PROGRAM?=true
# For multi-project applications, call advanced_program in the first project directory.
ifneq (,$(_MTB_RECIPE__IS_MULTI_CORE_APPLICATION))
_MTB_RECIPE__ADVANCED_PROGRAM_MAKE_CMD:=-C $(_MTB_RECIPE__IDE_PRJ_DIR_NAME) advanced_program MTB_APPLICATION_SUBPROJECTS=\"$(MTB_APPLICATION_SUBPROJECTS)\"
endif
ifeq ($(MTB_RECIPE__ATTACH_SERVER_TYPE),)
MTB_RECIPE__ATTACH_SERVER_TYPE=openocd
endif
_MTB_RECIPE__VSCODE_SVD_PATH:=$(DEVICE_$(DEVICE)_SVD)
_MTB_RECIPE__VSCODE_APPLICATION_SVD_PATH=$(patsubst ../%,%,$(_MTB_RECIPE__VSCODE_SVD_PATH))

vscode_generate: recipe_vscode_common_text_replacement_data_file recipe_vscode_common_metadata_file
vscode_generate: MTB_CORE__EXPORT_CMDLINE += -textdata $(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE) -metadata $(_MTB_RECIPE__IDE_VSCODE_COMMON_META_DATA_FILE)

_MTB_RECIPE__IDE_VSCODE_COMMON_META_DATA_FILE:=$(MTB_TOOLS__OUTPUT_CONFIG_DIR)/recipe_ide_vscode_common_meta.txt

recipe_vscode_common_text_replacement_data_file:
	$(call mtb__file_write,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ELF_FILE&&=$(_MTB_RECIPE__VSCODE_ELF_FILE))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__HEX_FILE&&=$(_MTB_RECIPE__VSCODE_HEX_FILE))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ELF_FILE_APPLICATION&&=$(_MTB_RECIPE__VSCODE_ELF_FILE_APPLICATION))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__HEX_FILE_APPLICATION&&=$(_MTB_RECIPE__VSCODE_HEX_FILE_APPLICATION))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__OPEN_OCD_FILE&&=$(_MTB_RECIPE__OPENOCD_DEVICE_CFG))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__OPENOCD_CHIP&&=$(_MTB_RECIPE__OPENOCD_CHIP_NAME))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__SVD_FILE_NAME&&=$(_MTB_RECIPE__VSCODE_SVD_PATH))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__APPLICATION_SVD_FILE_NAME&&=$(_MTB_RECIPE__VSCODE_APPLICATION_SVD_PATH))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__MTB_PATH&&=$(CY_TOOLS_DIR))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__OPENOCD_EXE_DIR_RELATIVE&&=$(CY_TOOL_openocd_EXE))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__OPENOCD_SCRIPTS_DIR_RELATIVE&&=$(CY_TOOL_openocd_scripts_SCRIPT))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__DEVICE_ATTACH&&=$(_MTB_RECIPE__JLINK_DEVICE_CFG_ATTACH))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__MODUS_SHELL_BASE&&=$(CY_TOOL_modus-shell_BASE))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ATTACH_SERVER_TYPE&&=$(MTB_RECIPE__ATTACH_SERVER_TYPE))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__GCC_BIN_DIR&&=$(_MTB_RECIPE__VSCODE_GCC_BASE_DIR)/bin)
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__PROBE_INTERFACE&&=$(_MTB_RECIPE__PROBE_INTERFACE))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__VSCODE_OPENOCD_PROBE_SERIAL_CMD&&=$(_MTB_RECIPE__OPENOCD_PROBE_SERIAL))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__PROBE_SERIAL&&=$(MTB_PROBE_SERIAL))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__OPENOCD_BOARD&&=$(_MTB_RECIPE__OPENOCD_BOARD))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__OPENOCD_PROBE_FREQUENCY_CMD&&=$(_MTB_RECIPE__OPENOCD_PROBE_FREQUENCY))

recipe_vscode_common_metadata_file:
	$(call mtb__file_write,$(_MTB_RECIPE__IDE_VSCODE_COMMON_META_DATA_FILE),)
ifneq (,$(_MTB_RECIPE__IS_MULTI_CORE_APPLICATION))
ifneq (,$(_MTB_RECIPE__IS_FIRST_PRJ))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_VSCODE_COMMON_META_DATA_FILE),TEMPLATE_REPLACE=$(_MTB_RECIPE__VSCODE_MULTI_CORE_APP_TASKS_JSON)=../.vscode/tasks.json)
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_VSCODE_COMMON_META_DATA_FILE),TEMPLATE_REPLACE=$(_MTB_RECIPE__VSCODE_MULTI_CORE_APP_LAUNCH_JSON)=../.vscode/launch.json)
else
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_VSCODE_COMMON_META_DATA_FILE),TEMPLATE_REPLACE=../.vscode=../.vscode)
endif
endif
ifeq ($(MTB_COMBINE_SIGN_$(_MTB_RECIPE__IDE_PRJ_DIR_NAME)_HEX_FILES),)
ifneq (,$(_MTB_RECIPE__IS_MULTI_CORE_APPLICATION))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_VSCODE_COMMON_META_DATA_FILE),TEMPLATE_REPLACE=$(_MTB_RECIPE__VSCODE_MULTI_CORE_PRJ_TASKS_JSON)=.vscode/tasks.json)
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_VSCODE_COMMON_META_DATA_FILE),TEMPLATE_REPLACE=$(_MTB_RECIPE__VSCODE_MULTI_CORE_PRJ_LAUNCH_JSON)=.vscode/launch.json)
else #(,$(_MTB_RECIPE__IS_MULTI_CORE_APPLICATION))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_VSCODE_COMMON_META_DATA_FILE),TEMPLATE_REPLACE=$(_MTB_RECIPE__VSCODE_SINGLE_CORE_APP_TASKS_JSON)=.vscode/tasks.json)
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_VSCODE_COMMON_META_DATA_FILE),TEMPLATE_REPLACE=$(_MTB_RECIPE__VSCODE_SINGLE_CORE_APP_LAUNCH_JSON)=.vscode/launch.json)
endif #(,$(_MTB_RECIPE__IS_MULTI_CORE_APPLICATION))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_VSCODE_COMMON_META_DATA_FILE),MERGE_LAUNCH_JSON=.vscode/launch.json=.vscode/launch.json)
endif

.PHONY: recipe_vscode_common_text_replacement_data_file recipe_vscode_common_metadata_file

##############################################
# Eclipse
##############################################
_MTB_RECIPE__ECLIPSE_OPENOCD_SVD_PATH:=$${cy_prj_path}/$(DEVICE_$(DEVICE)_SVD)
_MTB_RECIPE__ECLIPSE_SYM_FILE:=$${cy_prj_path}/$(_MTB_RECIPE__IDE_BUILD_PATH_RELATIVE)/$(APPNAME).$(MTB_RECIPE__SUFFIX_TARGET)
_MTB_RECIPE__ECLIPSE_PRJ_PROG_FILE:=$${cy_prj_path}/$(_MTB_RECIPE__IDE_BUILD_PATH_RELATIVE)/$(APPNAME)$(_MTB_RECIPE__PROG_FILE_SUFFIX).$(MTB_RECIPE__SUFFIX_PROGRAM)
_MTB_RECIPE__ECLIPSE_APP_PROG_FILE:=$${cy_prj_path}/../$(_MTB_RECIPE__IDE_COMBINED_HEX_RELATIVE)

# JLink path
ifneq (,$(MTB_CORE__JLINK_GDB_EXE))
_MTB_RECIPE__ECLIPSE_JLINK_EXE:=$(MTB_CORE__JLINK_GDB_EXE)
else
_MTB_RECIPE__ECLIPSE_JLINK_EXE:=$${jlink_path}/$${jlink_gdbserver}
endif

# GDB path
_MTB_RECIPE__ECLIPSE_GDB=$${cy_tools_path:CY_TOOL_arm-none-eabi-gdb_EXE}

# If a custom name needs to be provided for the IDE environment it can be specified by
# CY_IDE_PRJNAME. If CY_IDE_PRJNAME was not set on the command line, use APPNAME as the
# default. CY_IDE_PRJNAME can be important in some environments like eclipse where the
# name used within the project is not necessarily what the user created. This can happen
# in Eclipse if there is already a project with the desired name. In this case Eclipse
# will create its own name. That name must still be used for launch configurations instead
# of the name the user actually gave. It can also be necessary when there are multiple
# applications that get created for a single design. In either case we allow a custom name
# to be provided. If one is not provided, we will fallback to the default APPNAME.
ifeq ($(CY_IDE_PRJNAME),)
CY_IDE_PRJNAME=$(APPNAME)
ifeq ($(MTB_APPLICATION_NAME),)
_MTB_RECIPE__ECLIPSE_APPLICATION_NAME:=$(APPNAME)
else
_MTB_RECIPE__ECLIPSE_APPLICATION_NAME:=$(patsubst "%",%,$(MTB_APPLICATION_NAME))
endif
else
# in a multi-core application, CY_IDE_PRJNAME is name selected in the project-creator and should only apply to the project
_MTB_RECIPE__ECLIPSE_APPLICATION_NAME:=$(CY_IDE_PRJNAME)
endif

ifeq ($(MTB_TYPE),PROJECT)
_MTB_RECIPE__PROG_TARGET:=program_proj
ifneq ($(MTB_APPLICATION_SUBPROJECTS),)
_MTB_RECIPE__ECLIPSE_PROJECT_NAME=$(_MTB_RECIPE__ECLIPSE_APPLICATION_NAME).$(APPNAME)
endif
else #($(MTB_TYPE),PROJECT)
_MTB_RECIPE__ECLIPSE_PROJECT_NAME=$(CY_IDE_PRJNAME)
_MTB_RECIPE__PROG_TARGET:=program
endif #($(MTB_TYPE),PROJECT)

eclipse_generate: recipe_eclipse_common_text_replacement_data_file recipe_eclipse_common_regex_replacement_data_file
eclipse_generate: MTB_CORE__EXPORT_CMDLINE += -textdata $(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE) -textregexdata $(_MTB_RECIPE__ECLIPSE_COMMON_REGEX_DATA_FILE)

recipe_eclipse_common_text_replacement_data_file:
	$(call mtb__file_write,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__OPENOCD_CFG&&=$(_MTB_RECIPE__OPENOCD_DEVICE_CFG))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__OPENOCD_CHIP&&=$(_MTB_RECIPE__OPENOCD_CHIP_NAME))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__OPENOCD_RUN_RESTART_CMD_ATTACH_ECLIPSE&&=$(_MTB_RECIPE__OPENOCD_RUN_RESTART_CMD_ATTACH_ECLIPSE))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__SVD_PATH&&=$(_MTB_RECIPE__ECLIPSE_OPENOCD_SVD_PATH))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__SYM_FILE&&=$(_MTB_RECIPE__ECLIPSE_SYM_FILE))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__APP_PROG_FILE&&=$(_MTB_RECIPE__ECLIPSE_APP_PROG_FILE))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__PRJ_PROG_FILE&&=$(_MTB_RECIPE__ECLIPSE_PRJ_PROG_FILE))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_GDB&&=$(_MTB_RECIPE__ECLIPSE_GDB))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_JLINK_EXE&&=$(_MTB_RECIPE__ECLIPSE_JLINK_EXE))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__APP_NAME&&=$(_MTB_RECIPE__ECLIPSE_APPLICATION_NAME))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__PRJ_NAME&&=$(_MTB_RECIPE__ECLIPSE_PROJECT_NAME))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__PROG_TARGET&&=$(_MTB_RECIPE__PROG_TARGET))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__BUILD_NUM_PROCESSOR&&=$(_MTB_CORE___VSCODE_BUILD_NUM_PROCESSOR))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_OPENOCD_PROBE_SERIAL_CMD&&=$(if $(_MTB_RECIPE__OPENOCD_PROBE_SERIAL),-c &quot;$(_MTB_RECIPE__OPENOCD_PROBE_SERIAL)&quot;&#13;&#10;,))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__OPENOCD_BOARD&&=$(if $(_MTB_RECIPE__OPENOCD_BOARD),-c &quot;$(_MTB_RECIPE__OPENOCD_BOARD)&quot;&#13;&#10;,))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__PROBE_INTERFACE&&=$(_MTB_RECIPE__PROBE_INTERFACE))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__PROBE_SERIAL&&=$(MTB_PROBE_SERIAL))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__OPENOCD_PROBE_FREQUENCY_CMD&&=$(_MTB_RECIPE__OPENOCD_PROBE_FREQUENCY))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_MULTICORE_PRE_TARGET_COMMANDS&&=$(_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_MULTICORE_PRE_TARGET_COMMANDS))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_MULTICORE_POST_TARGET_COMMANDS&&=$(_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_MULTICORE_POST_TARGET_COMMANDS))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_MULTICORE_SECOND_CONFIG_NAME&&=$(_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_MULTICORE_SECOND_CONFIG_NAME))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_MULTICORE_THIRD_CONFIG_NAME&&=$(_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_MULTICORE_THIRD_CONFIG_NAME))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_MULTICORE_FOURTH_CONFIG_NAME&&=$(_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_MULTICORE_FOURTH_CONFIG_NAME))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_MULTICORE_FIFTH_CONFIG_NAME&&=$(_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_MULTICORE_FIFTH_CONFIG_NAME))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_MULTICORE_OTHER_RUN_COMMANDS&&=$(_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_MULTICORE_OTHER_RUN_COMMANDS))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_DO_CONTINUE&&=$(_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_DO_CONTINUE))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_DO_SECOND_RESET&&=$(_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_DO_SECOND_RESET))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_DO_DEBUG_IN_RAM&&=$(_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_DO_DEBUG_IN_RAM))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_GDB_CLIENT_OTHER_COMMANDS&&=$(_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_GDB_CLIENT_OTHER_COMMANDS))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_PRE_TARGET_COMMANDS&&=$(_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_PRE_TARGET_COMMANDS))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_POST_TARGET_COMMANDS&&=$(_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_POST_TARGET_COMMANDS))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_OTHER_RUN_COMMANDS&&=$(_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_OTHER_RUN_COMMANDS))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_LOAD_IMAGE&&=$(_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_LOAD_IMAGE))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_OTHER_INIT_COMMANDS&&=$(_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_OTHER_INIT_COMMANDS))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_SECOND_RESET_TYPE&&=$(_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_SECOND_RESET_TYPE))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_GDB_PORT_NUMBER&&=$(_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_GDB_PORT_NUMBER))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_STOP_AT&&=$(_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_STOP_AT))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__DEBUG_CERTIFICATE&&=$(if $(CY_DBG_CERTIFICATE_PATH),-c &quot;set DEBUG_CERTIFICATE $(CY_DBG_CERTIFICATE_PATH)&quot;&#13;&#10;,))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__DEBUG_CERTIFICATE_APPLICATION&&=$(if $(CY_DBG_CERTIFICATE_PATH),-c &quot;set DEBUG_CERTIFICATE $(CY_DBG_CERTIFICATE_PATH_APPLICATION)&quot;&#13;&#10;,))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_OPENOCD_ATTACH_DO_CONTINUE&&=$(_MTB_RECIPE__ECLIPSE_OPENOCD_ATTACH_DO_CONTINUE))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_OPENOCD_ATTACH_GDB_CLIENT_OTHER_COMMANDS&&=$(_MTB_RECIPE__ECLIPSE_OPENOCD_ATTACH_GDB_CLIENT_OTHER_COMMANDS))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_OPENOCD_ATTACH_PRE_TARGET_COMMANDS&&=$(_MTB_RECIPE__ECLIPSE_OPENOCD_ATTACH_PRE_TARGET_COMMANDS))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_OPENOCD_ATTACH_POST_TARGET_COMMANDS&&=$(_MTB_RECIPE__ECLIPSE_OPENOCD_ATTACH_POST_TARGET_COMMANDS))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_OPENOCD_ATTACH_OTHER_RUN_COMMANDS&&=$(_MTB_RECIPE__ECLIPSE_OPENOCD_ATTACH_OTHER_RUN_COMMANDS))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_OPENOCD_ATTACH_ATTR_BUILD_BEFORE_LAUNCH&&=$(_MTB_RECIPE__ECLIPSE_OPENOCD_ATTACH_ATTR_BUILD_BEFORE_LAUNCH))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_OPENOCD_ATTACH_PROJECT_BUILD_CONFIG_AUTO&&=$(_MTB_RECIPE__ECLIPSE_OPENOCD_ATTACH_PROJECT_BUILD_CONFIG_AUTO))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_OPENOCD_ATTACH_GDB_PORT_NUMBER&&=$(_MTB_RECIPE__ECLIPSE_OPENOCD_ATTACH_GDB_PORT_NUMBER))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_OPENOCD_ATTACH_SET_STOP_AT&&=$(_MTB_RECIPE__ECLIPSE_OPENOCD_ATTACH_SET_STOP_AT))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_OPENOCD_ATTACH_STOP_AT&&=$(_MTB_RECIPE__ECLIPSE_OPENOCD_ATTACH_STOP_AT))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_OPENOCD_ATTACH_MULTICORE_OTHER_RUN_COMMANDS&&=$(_MTB_RECIPE__ECLIPSE_OPENOCD_ATTACH_MULTICORE_OTHER_RUN_COMMANDS))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_OPENOCD_ATTACH_MULTICORE_GDB_PORT_NUMBER&&=$(_MTB_RECIPE__ECLIPSE_OPENOCD_ATTACH_MULTICORE_GDB_PORT_NUMBER))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_MULTICORE_SECOND_CONFIG_NAME&&=$(_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_MULTICORE_SECOND_CONFIG_NAME))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_MULTICORE_THIRD_CONFIG_NAME&&=$(_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_MULTICORE_THIRD_CONFIG_NAME))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_MULTICORE_FOURTH_CONFIG_NAME&&=$(_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_MULTICORE_FOURTH_CONFIG_NAME))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_MULTICORE_FIFTH_CONFIG_NAME&&=$(_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_MULTICORE_FIFTH_CONFIG_NAME))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_JLINK_LAUNCH_GROUP_0_ACTION&&=$(_MTB_RECIPE__ECLIPSE_JLINK_LAUNCH_GROUP_0_ACTION))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_GDB_PORT_NUMBER&&=$(_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_GDB_PORT_NUMBER))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_SWO_PORT_NUMBER&&=$(_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_SWO_PORT_NUMBER))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_TELNET_PORT_NUMBER&&=$(_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_TELNET_PORT_NUMBER))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_OTHER_RUN_COMMANDS&&=$(_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_OTHER_RUN_COMMANDS))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_LOAD_IMAGE&&=$(_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_LOAD_IMAGE))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_GDB_CLIENT_OTHER_COMMANDS&&=$(_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_GDB_CLIENT_OTHER_COMMANDS))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_FIRST_RESET_SPEED&&=$(_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_FIRST_RESET_SPEED))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_ALLOCATE_SEMIHOSTING_CONSOLE&&=$(_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_ALLOCATE_SEMIHOSTING_CONSOLE))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_SECOND_RESET_TYPE&&=$(_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_SECOND_RESET_TYPE))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_GDB_SERVER_DEVICE_NAME&&=$(_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_GDB_SERVER_DEVICE_NAME))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_FIRST_RESET_TYPE&&=$(_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_FIRST_RESET_TYPE))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_INTERFACE_SPEED&&=$(_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_INTERFACE_SPEED))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_JLINK_ATTACH_GDB_PORT_NUMBER&&=$(_MTB_RECIPE__ECLIPSE_JLINK_ATTACH_GDB_PORT_NUMBER))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_JLINK_ATTACH_SWO_PORT_NUMBER&&=$(_MTB_RECIPE__ECLIPSE_JLINK_ATTACH_SWO_PORT_NUMBER))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_JLINK_ATTACH_TELNET_PORT_NUMBER&&=$(_MTB_RECIPE__ECLIPSE_JLINK_ATTACH_TELNET_PORT_NUMBER))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_JLINK_ATTACH_OTHER_RUN_COMMANDS&&=$(_MTB_RECIPE__ECLIPSE_JLINK_ATTACH_OTHER_RUN_COMMANDS))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_JLINK_ATTACH_FIRST_RESET_TYPE&&=$(_MTB_RECIPE__ECLIPSE_JLINK_ATTACH_FIRST_RESET_TYPE))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_JLINK_ATTACH_SECOND_RESET_TYPE&&=$(_MTB_RECIPE__ECLIPSE_JLINK_ATTACH_SECOND_RESET_TYPE))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_JLINK_ATTACH_ATTR_BUILD_BEFORE_LAUNCH&&=$(_MTB_RECIPE__ECLIPSE_JLINK_ATTACH_ATTR_BUILD_BEFORE_LAUNCH))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_JLINK_ATTACH_GDB_CLIENT_OTHER_COMMANDS&&=$(_MTB_RECIPE__ECLIPSE_JLINK_ATTACH_GDB_CLIENT_OTHER_COMMANDS))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_JLINK_ATTACH_GDB_SERVER_DEVICE_NAME&&=$(_MTB_RECIPE__ECLIPSE_JLINK_ATTACH_GDB_SERVER_DEVICE_NAME))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_JLINK_ATTACH_ENABLE_SEMIHOSTING&&=$(_MTB_RECIPE__ECLIPSE_JLINK_ATTACH_ENABLE_SEMIHOSTING))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_JLINK_ATTACH_ENABLE_SEMIHOSTING_GDB_CLIENT&&=$(_MTB_RECIPE__ECLIPSE_JLINK_ATTACH_ENABLE_SEMIHOSTING_GDB_CLIENT))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_JLINK_ATTACH_ENABLE_SEMIHOSTING_TELNET_CLIENT&&=$(_MTB_RECIPE__ECLIPSE_JLINK_ATTACH_ENABLE_SEMIHOSTING_TELNET_CLIENT))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_JLINK_ATTACH_INTERFACE_SPEED&&=$(_MTB_RECIPE__ECLIPSE_JLINK_ATTACH_INTERFACE_SPEED))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_MULTICORE_OTHER_RUN_COMMANDS&&=$(_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_MULTICORE_OTHER_RUN_COMMANDS))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_MULTICORE_GDB_CLIENT_OTHER_COMMANDS&&=$(_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_MULTICORE_GDB_CLIENT_OTHER_COMMANDS))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__QSPI_CFG_PATH&&=$(_MTB_RECIPE__OPENOCD_QSPI_CFG_PATH_WITH_FLAG))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__QSPI_CFG_PATH_APPLICATION&&=$(_MTB_RECIPE__OPENOCD_QSPI_CFG_PATH_APPLICATION_WITH_FLAG))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__QSPI_FLASHLOADER&&=$(_MTB_RECIPE__OPENOCD_QSPI_FLASHLOADER_WITH_FLAG))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__QSPI_FLASHLOADER_APPLICATION&&=$(_MTB_RECIPE__OPENOCD_QSPI_FLASHLOADER_APPLICATION_WITH_FLAG))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__DEBUG_CERTIFICATE&&=$(if $(CY_DBG_CERTIFICATE_PATH),-c &quot;set DEBUG_CERTIFICATE $(CY_DBG_CERTIFICATE_PATH)&quot;&#13;&#10;,))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_MTB_RECIPE__DEBUG_CERTIFICATE_APPLICATION&&=$(if $(CY_DBG_CERTIFICATE_PATH),-c &quot;set DEBUG_CERTIFICATE $(CY_DBG_CERTIFICATE_PATH_APPLICATION)&quot;&#13;&#10;,))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_APP_NAME&&=$(_MTB_RECIPE__ECLIPSE_APPLICATION_NAME))
	$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMMON_TEXT_DATA_FILE),&&_PRJ_NAME&&=$(_MTB_RECIPE__ECLIPSE_PROJECT_NAME))

recipe_eclipse_common_regex_replacement_data_file:
ifeq (NONE,$(_MTB_RECIPE__ECLIPSE_JLINK_LAUNCH_GROUP_0_ACTION))
	$(call mtb__file_write,$(_MTB_RECIPE__ECLIPSE_COMMON_REGEX_DATA_FILE),^.*//multi-core action param 0//.*$$=)
else
	$(call mtb__file_write,$(_MTB_RECIPE__ECLIPSE_COMMON_REGEX_DATA_FILE),^(.*)//multi-core action param 0//(.*)$$=\1\2)
endif

.PHONY: recipe_eclipse_common_text_replacement_data_file recipe_eclipse_common_regex_replacement_data_file

##############################################
# EW
##############################################
_MTB_RECIPE__IDE_DFP_DATA_FILE=$(MTB_TOOLS__OUTPUT_CONFIG_DIR)/recipe_ide_dfp_data.txt
ewarm8: MTB_CORE__EXPORT_CMDLINE+= -dfp_data $(_MTB_RECIPE__IDE_DFP_DATA_FILE)
ewarm8: recipe_ewarm_dfp_data_file

recipe_ewarm_dfp_data_file:
	$(call mtb__file_write,$(_MTB_RECIPE__IDE_DFP_DATA_FILE),DEVICE=$(DEVICE)$(_MTB_RECIPE__IAR_CORE_SUFFIX))

.PHONY: recipe_ewarm_dfp_data_file


##############################################
# Combiner/Signer Integration
##############################################

ifneq ($(MTB_COMBINE_SIGN_$(_MTB_RECIPE__IDE_PRJ_DIR_NAME)_HEX_FILES),)
_MTB_RECIPE__IDE_COMBINE_SIGN_TEXT_DATA_FILE=$(MTB_TOOLS__OUTPUT_CONFIG_DIR)/recipe_ide_combine_sign_text_data.txt

eclipse_generate vscode_generate: MTB_CORE__EXPORT_CMDLINE += -textdata $(_MTB_RECIPE__IDE_COMBINE_SIGN_TEXT_DATA_FILE)
eclipse_generate vscode_generate: recipe_ide_combine_sign_text_replacement

recipe_ide_combine_sign_text_replacement:
	$(call mtb__file_write,$(_MTB_RECIPE__IDE_COMBINE_SIGN_TEXT_DATA_FILE),)
	$(foreach index,$(MTB_COMBINE_SIGN_$(_MTB_RECIPE__IDE_PRJ_DIR_NAME)_HEX_FILES),$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMBINE_SIGN_TEXT_DATA_FILE),&&MTB_COMBINE_SIGN_$(index)_PRJ_NAME&&=$(MTB_COMBINE_SIGN_$(index)_PRJ_NAME)))
	$(foreach index,$(MTB_COMBINE_SIGN_$(_MTB_RECIPE__IDE_PRJ_DIR_NAME)_HEX_FILES),$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMBINE_SIGN_TEXT_DATA_FILE),&&MTB_COMBINE_SIGN_$(index)_CONFIG_NAME&&=$(MTB_COMBINE_SIGN_$(index)_CONFIG_NAME)))
	$(foreach index,$(MTB_COMBINE_SIGN_$(_MTB_RECIPE__IDE_PRJ_DIR_NAME)_HEX_FILES),$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMBINE_SIGN_TEXT_DATA_FILE),&&MTB_COMBINE_SIGN_$(index)_ECLIPSE_HEX_PATH&&=$${cy_prj_path}/$(MTB_COMBINE_SIGN_$(index)_HEX_PATH)))
	$(foreach index,$(MTB_COMBINE_SIGN_$(_MTB_RECIPE__IDE_PRJ_DIR_NAME)_HEX_FILES),$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMBINE_SIGN_TEXT_DATA_FILE),&&MTB_COMBINE_SIGN_$(index)_VSCODE_HEX_PATH&&=$(MTB_COMBINE_SIGN_$(index)_HEX_PATH)))
	$(foreach index,$(MTB_COMBINE_SIGN_$(_MTB_RECIPE__IDE_PRJ_DIR_NAME)_HEX_FILES),$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMBINE_SIGN_TEXT_DATA_FILE),&&MTB_COMBINE_SIGN_$(index)_EXTRA_ELF_PATH&&=$(if $(MTB_COMBINE_SIGN_$(index)_EXTRA_ELF_PATH),add-symbol-file $(MTB_COMBINE_SIGN_$(index)_EXTRA_ELF_PATH),)))
	$(foreach index,$(MTB_COMBINE_SIGN_$(_MTB_RECIPE__IDE_PRJ_DIR_NAME)_HEX_FILES),$(call mtb__file_append,$(_MTB_RECIPE__IDE_COMBINE_SIGN_TEXT_DATA_FILE),&&MTB_COMBINE_SIGN_$(index)_VSCODE_EXTRA_ELF_PATH&&=$(if $(MTB_COMBINE_SIGN_$(index)_EXTRA_ELF_PATH),"add-symbol-file $(MTB_COMBINE_SIGN_$(index)_EXTRA_ELF_PATH)",)))


_MTB_RECIPE__VSCODE_COMBINE_SIGN_MEATA_DATA_FILE=$(MTB_TOOLS__OUTPUT_CONFIG_DIR)/vscode_combine_sign_meta_data.txt

vscode_generate: MTB_CORE__EXPORT_CMDLINE += -metadata $(_MTB_RECIPE__VSCODE_COMBINE_SIGN_MEATA_DATA_FILE)
vscode_generate: recipe_vscode_combine_sign_meta

# Build multicore task list (base list without lib_mgr and erase tasks)
_MTB_RECIPE__VSCODE_MULTICORE_COMBINE_SIGN_TASKS_LIST := \
    .vscode/tasks.json=.vscode/tasks_partial.json \
    $(foreach index,$(MTB_COMBINE_SIGN_$(_MTB_RECIPE__IDE_PRJ_DIR_NAME)_HEX_FILES),.vscode/tasks_$(index).json)

# Build singlecore task list (extends multicore list)
_MTB_RECIPE__VSCODE_SINGLECORE_COMBINE_SIGN_TASKS_LIST := \
    $(_MTB_RECIPE__VSCODE_MULTICORE_COMBINE_SIGN_TASKS_LIST)

# check if task_lib_mgr exist
ifneq ($(wildcard $(_MTB_RECIPE__IDE_CORE_SCRIPT_DIR)/vscode/task_lib_mgr.json),)
_MTB_RECIPE__VSCODE_SINGLECORE_COMBINE_SIGN_TASKS_LIST += .vscode/task_lib_mgr.json
ifeq ($(filter internal,$(_MTB_RECIPE__VSCODE_TASKS_ERASE_MEMORIES_SUPPORTED)),internal)
_MTB_RECIPE__VSCODE_SINGLECORE_COMBINE_SIGN_TASKS_LIST += .vscode/tasks_erase_device.json
endif
ifeq ($(filter external,$(_MTB_RECIPE__VSCODE_TASKS_ERASE_MEMORIES_SUPPORTED)),external)
_MTB_RECIPE__VSCODE_SINGLECORE_COMBINE_SIGN_TASKS_LIST += .vscode/tasks_erase_all.json
endif
endif

recipe_vscode_combine_sign_meta:
	$(call mtb__file_write,$(_MTB_RECIPE__VSCODE_COMBINE_SIGN_MEATA_DATA_FILE),)
	$(call mtb__file_append,$(_MTB_RECIPE__VSCODE_COMBINE_SIGN_MEATA_DATA_FILE),TEMPLATE_REPLACE=$(_MTB_RECIPE__VSCODE_CS_LAUNCH_JSON)=.vscode/launch_&&IDX&&.json)
	$(call mtb__file_append,$(_MTB_RECIPE__VSCODE_COMBINE_SIGN_MEATA_DATA_FILE),TEMPLATE_REPEAT=.vscode/launch_&&IDX&&.json=$(MTB_COMBINE_SIGN_$(_MTB_RECIPE__IDE_PRJ_DIR_NAME)_HEX_FILES))
	$(call mtb__file_append,$(_MTB_RECIPE__VSCODE_COMBINE_SIGN_MEATA_DATA_FILE),MERGE_LAUNCH_JSON=.vscode/launch.json=$(foreach index,$(MTB_COMBINE_SIGN_$(_MTB_RECIPE__IDE_PRJ_DIR_NAME)_HEX_FILES),.vscode/launch_$(index).json))
	$(call mtb__file_append,$(_MTB_RECIPE__VSCODE_COMBINE_SIGN_MEATA_DATA_FILE),TEMPLATE_REPLACE=$(_MTB_RECIPE__IDE_CORE_SCRIPT_DIR)/vscode/tasks_partial.json=.vscode/tasks_partial.json)
	$(call mtb__file_append,$(_MTB_RECIPE__VSCODE_COMBINE_SIGN_MEATA_DATA_FILE),TEMPLATE_REPLACE=$(_MTB_RECIPE__VSCODE_CS_TASKS_JSON)=.vscode/tasks_&&IDX&&.json)
	$(call mtb__file_append,$(_MTB_RECIPE__VSCODE_COMBINE_SIGN_MEATA_DATA_FILE),TEMPLATE_REPEAT=.vscode/tasks_&&IDX&&.json=$(MTB_COMBINE_SIGN_$(_MTB_RECIPE__IDE_PRJ_DIR_NAME)_HEX_FILES))
ifneq (,$(_MTB_RECIPE__IS_MULTI_CORE_APPLICATION))
# multicore-core projects
	$(call mtb__file_append,$(_MTB_RECIPE__VSCODE_COMBINE_SIGN_MEATA_DATA_FILE),MERGE_TASKS_JSON=$(_MTB_RECIPE__VSCODE_MULTICORE_COMBINE_SIGN_TASKS_LIST))
else
# single-core projects
ifeq ($(filter internal,$(_MTB_RECIPE__VSCODE_TASKS_ERASE_MEMORIES_SUPPORTED)),internal)
	$(call mtb__file_append,$(_MTB_RECIPE__VSCODE_COMBINE_SIGN_MEATA_DATA_FILE),TEMPLATE_REPLACE=$(_MTB_RECIPE__IDE_CORE_SCRIPT_DIR)/vscode/task_erase_device.json=.vscode/tasks_erase_device.json)
endif
ifeq ($(filter external,$(_MTB_RECIPE__VSCODE_TASKS_ERASE_MEMORIES_SUPPORTED)),external)
	$(call mtb__file_append,$(_MTB_RECIPE__VSCODE_COMBINE_SIGN_MEATA_DATA_FILE),TEMPLATE_REPLACE=$(_MTB_RECIPE__IDE_CORE_SCRIPT_DIR)/vscode/task_erase_all.json=.vscode/tasks_erase_all.json)
endif
	$(call mtb__file_append,$(_MTB_RECIPE__VSCODE_COMBINE_SIGN_MEATA_DATA_FILE),TEMPLATE_REPLACE=$(_MTB_RECIPE__IDE_CORE_SCRIPT_DIR)/vscode/task_lib_mgr.json=.vscode/task_lib_mgr.json)
	$(call mtb__file_append,$(_MTB_RECIPE__VSCODE_COMBINE_SIGN_MEATA_DATA_FILE),MERGE_TASKS_JSON=$(_MTB_RECIPE__VSCODE_SINGLECORE_COMBINE_SIGN_TASKS_LIST))
endif

.PHONY: recipe_ide_combine_sign_text_replacement recipe_vscode_combine_sign_meta

endif #ifneq ($(MTB_COMBINE_SIGN_$(_MTB_RECIPE__IDE_PRJ_DIR_NAME)_HEX_FILES),)
