################################################################################
# \file defines_common.mk
#
# \brief
# Common variables and targets for defines.mk
#
################################################################################
# \copyright
# Copyright (c) 2018-2026, Infineon Technologies AG, or an affiliate of
# Infineon Technologies AG. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

ifeq ($(WHICHFILE),true)
$(info Processing $(lastword $(MAKEFILE_LIST)))
endif

MTB_RECIPE__MEMREPORT_SUPPORT:=1 2

################################################################################
# BSP
################################################################################

ifneq (1,$(words $(DEVICE_$(DEVICE)_CORES)))
_MTB_RECIPE__IS_MULTI_CORE_DEVICE:=true
endif

ifneq (,$(filter StandardSecure,$(DEVICE_$(DEVICE)_FEATURES)))
_MTB_RECIPE__IS_SECURE_DEVICE:=true
endif
ifneq (,$(filter SecureBoot,$(DEVICE_$(DEVICE)_FEATURES)))
_MTB_RECIPE__IS_SECURE_DEVICE:=true
endif

_MTB_RECIPE__DEVICE_DIE:=$(DEVICE_$(DEVICE)_DIE)

_MTB_RECIPE__DEVICE_FLASH_KB:=$(DEVICE_$(DEVICE)_FLASH_KB)

ifeq ($(MTB_RECIPE__CORE),CM55)
MTB_RECIPE__VFP_SELECT_DEFAULT=hardfp
endif

ifneq ($(filter $(_MTB_RECIPE__DEVICE_DIE)_PSVP,$(DEFINES)),)
_MTB_RECIPE__OPENOCD_BOARD=set BOARD psvp
endif

_MTB_RECIPE__ECLIPSE_QUOT=&quot;
_MTB_RECIPE__ECLIPSE_NEWLINE:=&\#13;&\#10;

_MTB_RECIPE__ECLIPSE_OPENOCD_BOARD=$(if $(_MTB_RECIPE__OPENOCD_BOARD),-c &quot;$(_MTB_RECIPE__OPENOCD_BOARD)&quot;$(_MTB_RECIPE__ECLIPSE_NEWLINE),)
_MTB_RECIPE__ECLIPSE_OPENOCD_PROBE_SERIAL_CMD=$(if $(_MTB_RECIPE__OPENOCD_PROBE_SERIAL),-c &quot;$(_MTB_RECIPE__OPENOCD_PROBE_SERIAL)&quot;$(_MTB_RECIPE__ECLIPSE_NEWLINE),)

# Target core suffix for OpenOCD RTOS config command (e.g. cm33, cm4, cm0p).
# Recipes that target a different core must override this in their defines.mk.
_MTB_RECIPE__OPENOCD_DEBUG_TARGET_CORE?=cm33

# OpenOCD Debug
_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_SECOND_RESET_TYPE?=init
_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_OTHER_INIT_COMMANDS?=
_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_GDB_PORT_NUMBER?=3333
_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_STOP_AT?=true
_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_DO_CONTINUE?=true
_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_DO_SECOND_RESET?=true
ifeq (ram,$(APPTYPE))
_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_DO_DEBUG_IN_RAM?=true
else
_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_DO_DEBUG_IN_RAM?=false
endif

_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_GDB_CLIENT_OTHER_COMMANDS?=set mem inaccessible-by-default off$(_MTB_RECIPE__ECLIPSE_NEWLINE)set remotetimeout 25

ifndef _MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_PRE_TARGET_COMMANDS
_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_PRE_TARGET_COMMANDS=$(_MTB_RECIPE__ECLIPSE_OPENOCD_BOARD)$(_MTB_RECIPE__ECLIPSE_OPENOCD_PROBE_SERIAL_CMD)
_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_PRE_TARGET_COMMANDS+=-c $(_MTB_RECIPE__ECLIPSE_QUOT)transport select $(_MTB_RECIPE__PROBE_INTERFACE)$(_MTB_RECIPE__ECLIPSE_QUOT)$(_MTB_RECIPE__ECLIPSE_NEWLINE)
endif

ifndef _MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_POST_TARGET_COMMANDS
_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_POST_TARGET_COMMANDS=-c $(_MTB_RECIPE__ECLIPSE_QUOT)$(_MTB_RECIPE__OPENOCD_CHIP_NAME).$(_MTB_RECIPE__OPENOCD_DEBUG_TARGET_CORE) configure -rtos auto -rtos-wipe-on-reset-halt 1$(_MTB_RECIPE__ECLIPSE_QUOT)$(_MTB_RECIPE__ECLIPSE_NEWLINE)
_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_POST_TARGET_COMMANDS+=-c $(_MTB_RECIPE__ECLIPSE_QUOT)gdb_breakpoint_override hard$(_MTB_RECIPE__ECLIPSE_QUOT)$(_MTB_RECIPE__ECLIPSE_NEWLINE)
_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_POST_TARGET_COMMANDS+=-c $(_MTB_RECIPE__ECLIPSE_QUOT)init; reset init;$(_MTB_RECIPE__OPENOCD_PROBE_FREQUENCY)$(_MTB_RECIPE__ECLIPSE_QUOT)
endif

_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_LOAD_IMAGE?=true

# OpenOCD Attach
_MTB_RECIPE__ECLIPSE_OPENOCD_ATTACH_PROJECT_BUILD_CONFIG_AUTO?=true
_MTB_RECIPE__ECLIPSE_OPENOCD_ATTACH_GDB_PORT_NUMBER?=3333
_MTB_RECIPE__ECLIPSE_OPENOCD_ATTACH_DO_CONTINUE?=false
_MTB_RECIPE__ECLIPSE_OPENOCD_ATTACH_ATTR_BUILD_BEFORE_LAUNCH?=0
_MTB_RECIPE__ECLIPSE_OPENOCD_ATTACH_GDB_CLIENT_OTHER_COMMANDS?=set mem inaccessible-by-default off$(_MTB_RECIPE__ECLIPSE_NEWLINE)set remotetimeout 25
_MTB_RECIPE__ECLIPSE_OPENOCD_ATTACH_SET_STOP_AT?=false
_MTB_RECIPE__ECLIPSE_OPENOCD_ATTACH_STOP_AT?=

ifndef _MTB_RECIPE__ECLIPSE_OPENOCD_ATTACH_PRE_TARGET_COMMANDS
_MTB_RECIPE__ECLIPSE_OPENOCD_ATTACH_PRE_TARGET_COMMANDS=-c $(_MTB_RECIPE__ECLIPSE_QUOT)set ENABLE_ACQUIRE 0$(_MTB_RECIPE__ECLIPSE_QUOT)$(_MTB_RECIPE__ECLIPSE_NEWLINE)
_MTB_RECIPE__ECLIPSE_OPENOCD_ATTACH_PRE_TARGET_COMMANDS+=$(_MTB_RECIPE__ECLIPSE_OPENOCD_BOARD)$(_MTB_RECIPE__ECLIPSE_OPENOCD_PROBE_SERIAL_CMD)
_MTB_RECIPE__ECLIPSE_OPENOCD_ATTACH_PRE_TARGET_COMMANDS+=-c $(_MTB_RECIPE__ECLIPSE_QUOT)transport select $(_MTB_RECIPE__PROBE_INTERFACE)$(_MTB_RECIPE__ECLIPSE_QUOT)$(_MTB_RECIPE__ECLIPSE_NEWLINE)
endif

ifndef _MTB_RECIPE__ECLIPSE_OPENOCD_ATTACH_POST_TARGET_COMMANDS
_MTB_RECIPE__ECLIPSE_OPENOCD_ATTACH_POST_TARGET_COMMANDS=-c $(_MTB_RECIPE__ECLIPSE_QUOT)$(_MTB_RECIPE__OPENOCD_CHIP_NAME).$(_MTB_RECIPE__OPENOCD_DEBUG_TARGET_CORE) configure -rtos auto -rtos-wipe-on-reset-halt 1$(_MTB_RECIPE__ECLIPSE_QUOT)$(_MTB_RECIPE__ECLIPSE_NEWLINE)
_MTB_RECIPE__ECLIPSE_OPENOCD_ATTACH_POST_TARGET_COMMANDS+=-c $(_MTB_RECIPE__ECLIPSE_QUOT)gdb_breakpoint_override hard$(_MTB_RECIPE__ECLIPSE_QUOT)$(_MTB_RECIPE__ECLIPSE_NEWLINE)
_MTB_RECIPE__ECLIPSE_OPENOCD_ATTACH_POST_TARGET_COMMANDS+=-c $(_MTB_RECIPE__ECLIPSE_QUOT)init$(_MTB_RECIPE__ECLIPSE_QUOT)
endif

_MTB_RECIPE__ECLIPSE_OPENOCD_ATTACH_OTHER_RUN_COMMANDS?=$(_MTB_RECIPE__OPENOCD_RUN_RESTART_CMD_ATTACH_ECLIPSE)

# JLINK Debug
_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_GDB_PORT_NUMBER?=2334
_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_SWO_PORT_NUMBER?=2335
_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_TELNET_PORT_NUMBER?=2336
_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_GDB_CLIENT_OTHER_COMMANDS?=set mem inaccessible-by-default off
_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_FIRST_RESET_SPEED?=1000
_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_ALLOCATE_SEMIHOSTING_CONSOLE?=false
_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_SECOND_RESET_TYPE?=
_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_LOAD_IMAGE?=true
_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_OTHER_RUN_COMMANDS?=
_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_FIRST_RESET_TYPE?=2

# JLINK Attach
_MTB_RECIPE__ECLIPSE_JLINK_ATTACH_ATTR_BUILD_BEFORE_LAUNCH?=0
_MTB_RECIPE__ECLIPSE_JLINK_ATTACH_GDB_PORT_NUMBER?=2334
_MTB_RECIPE__ECLIPSE_JLINK_ATTACH_SWO_PORT_NUMBER?=2335
_MTB_RECIPE__ECLIPSE_JLINK_ATTACH_TELNET_PORT_NUMBER?=2336
_MTB_RECIPE__ECLIPSE_JLINK_ATTACH_ENABLE_SEMIHOSTING?=true
_MTB_RECIPE__ECLIPSE_JLINK_ATTACH_ENABLE_SEMIHOSTING_GDB_CLIENT?=true
_MTB_RECIPE__ECLIPSE_JLINK_ATTACH_ENABLE_SEMIHOSTING_TELNET_CLIENT?=true
_MTB_RECIPE__ECLIPSE_JLINK_ATTACH_GDB_CLIENT_OTHER_COMMANDS?=set mem inaccessible-by-default off
_MTB_RECIPE__ECLIPSE_JLINK_ATTACH_FIRST_RESET_TYPE?=2
_MTB_RECIPE__ECLIPSE_JLINK_ATTACH_SECOND_RESET_TYPE?=2

_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_INTERFACE_SPEED?=auto
_MTB_RECIPE__ECLIPSE_JLINK_ATTACH_INTERFACE_SPEED?=auto

# JLink Launch Group
_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_MULTICORE_GDB_CLIENT_OTHER_COMMANDS?=set mem inaccessible-by-default off
_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_MULTICORE_OTHER_RUN_COMMANDS?=flushregs
_MTB_RECIPE__ECLIPSE_OPENOCD_ATTACH_MULTICORE_GDB_PORT_NUMBER?=3334
_MTB_RECIPE__ECLIPSE_JLINK_LAUNCH_GROUP_0_ACTION?=NONE